### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by maina360** [brysonpayne/LearnJava#1]
Hi Bryson,
I have to say your book is well written, I bought to use it as a refresher and I like so far. Anyway on page 68 under the subtitle Allowing users to press enter to guess you have referred to the guess button instead of the text field. It's nothing big but I thought I should point that out so you can add it to updates or errata!

Thank you for a wonderful book.

**Comment by brysonpayne** [comment]
Maina,
Thank you for the kind words, and for catching the error - I'll send a note to the publisher for the next printing - No Starch Press is great to work with, they fix errors before each new printing, and we're close to a second run. 
Thanks again for your help, and I'm glad you're enjoying Learn Java the Easy Way :).
Bryson
